# Generated by Django 5.0.3 on 2024-04-07 12:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('favorited', '0003_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='favorite',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='shoppingcart',
            unique_together=set(),
        ),
    ]
