# Generated by Django 5.0.3 on 2024-04-07 13:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('favorited', '0005_alter_favorite_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='favorite',
            unique_together=set(),
        ),
    ]
